# Generated by Django 3.1.7 on 2021-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('D', '1'), ('P', '2'), ('E', '3'), ('J', '4'), ('O', 'None')], max_length=7, verbose_name='Priority'),
        ),
    ]
